import { MuscleGroup } from './types';

// Material que necesita cada ejercicio — se usa para filtrar por el equipo
// disponible del usuario (ver TrainingModel.equipment en el User Model).
// Una etiqueta por ejercicio (la principal), no una lista — mantiene el
// filtrado simple y determinista.
export type ExerciseEquipment = 'bodyweight' | 'dumbbell' | 'barbell' | 'machine' | 'cable' | 'kettlebell';

export type ExerciseEntry = { name: string; equipment: ExerciseEquipment };

// Niveles de acceso a material que puede declarar el usuario por chat —
// vocabulario fijo y pequeño a propósito, así la IA solo tiene que elegir
// uno de estos tres, nunca inventar una lista de equipo libre.
export type EquipmentLevel = 'gym' | 'home_basic' | 'bodyweight_only';

// Qué tipos de ejercicio caben dentro de cada nivel — decidido aquí, de
// forma fija, no por la IA (mismo criterio que el resto del motor).
export const EQUIPMENT_ELIGIBLE: Record<EquipmentLevel, ExerciseEquipment[]> = {
  gym: ['bodyweight', 'dumbbell', 'barbell', 'machine', 'cable', 'kettlebell'],
  home_basic: ['bodyweight', 'dumbbell', 'kettlebell'],
  bodyweight_only: ['bodyweight'],
};

export const EXERCISE_DB: Record<MuscleGroup, ExerciseEntry[]> = {
  pecho: [
    { name: 'Bench press', equipment: 'barbell' },
    { name: 'Dumbbell bench press', equipment: 'dumbbell' },
    { name: 'Incline barbell press', equipment: 'barbell' },
    { name: 'Incline dumbbell press', equipment: 'dumbbell' },
    { name: 'Decline press', equipment: 'barbell' },
    { name: 'Dumbbell flyes', equipment: 'dumbbell' },
    { name: 'Cable crossover', equipment: 'cable' },
    { name: 'Machine chest press', equipment: 'machine' },
    { name: 'Dips', equipment: 'bodyweight' },
    { name: 'Pec deck', equipment: 'machine' },
    { name: 'Push-ups', equipment: 'bodyweight' },
    { name: 'Weighted push-ups', equipment: 'bodyweight' },
    { name: 'Pullover', equipment: 'dumbbell' },
    { name: 'Close-grip bench press', equipment: 'barbell' },
    { name: 'Svend press', equipment: 'dumbbell' },
    { name: 'Single-arm dumbbell press', equipment: 'dumbbell' },
    { name: 'Floor press', equipment: 'barbell' },
    { name: 'Landmine press', equipment: 'barbell' },
  ],
  espalda: [
    { name: 'Pull-ups', equipment: 'bodyweight' },
    { name: 'Chin-ups', equipment: 'bodyweight' },
    { name: 'Weighted pull-ups', equipment: 'bodyweight' },
    { name: 'Lat pulldown', equipment: 'cable' },
    { name: 'Close-grip pulldown', equipment: 'cable' },
    { name: 'Barbell row', equipment: 'barbell' },
    { name: 'Dumbbell row', equipment: 'dumbbell' },
    { name: 'Machine row', equipment: 'machine' },
    { name: 'Low cable row', equipment: 'cable' },
    { name: 'T-bar row', equipment: 'barbell' },
    { name: 'Face pull', equipment: 'cable' },
    { name: 'Pendlay row', equipment: 'barbell' },
    { name: 'Australian pull-up', equipment: 'bodyweight' },
    { name: 'Inverted row', equipment: 'bodyweight' },
    { name: 'Cable pullover', equipment: 'cable' },
    { name: 'Straight-arm pulldown', equipment: 'cable' },
    { name: 'Barbell shrug', equipment: 'barbell' },
    { name: 'Meadows row', equipment: 'barbell' },
  ],
  lumbar: [
    { name: 'Conventional deadlift', equipment: 'barbell' },
    { name: 'Romanian deadlift', equipment: 'barbell' },
    { name: 'Sumo deadlift', equipment: 'barbell' },
    { name: 'Stiff-leg deadlift', equipment: 'barbell' },
    { name: 'Hyperextensions', equipment: 'machine' },
    { name: 'Weighted hyperextensions', equipment: 'machine' },
    { name: 'Good morning', equipment: 'barbell' },
    { name: 'Superman', equipment: 'bodyweight' },
    { name: 'Machine back extension', equipment: 'machine' },
    { name: 'Trap bar deadlift', equipment: 'barbell' },
    { name: 'Deficit deadlift', equipment: 'barbell' },
    { name: 'Kettlebell swing', equipment: 'kettlebell' },
  ],
  core: [
    { name: 'Plank', equipment: 'bodyweight' },
    { name: 'Side plank', equipment: 'bodyweight' },
    { name: 'Weighted plank', equipment: 'bodyweight' },
    { name: 'Crunch', equipment: 'bodyweight' },
    { name: 'Cable crunch', equipment: 'cable' },
    { name: 'Reverse crunch', equipment: 'bodyweight' },
    { name: 'Leg raise', equipment: 'bodyweight' },
    { name: 'Hanging leg raise', equipment: 'bodyweight' },
    { name: 'Ab wheel rollout', equipment: 'bodyweight' },
    { name: 'Dead bug', equipment: 'bodyweight' },
    { name: 'Pallof press', equipment: 'cable' },
    { name: 'Russian twist', equipment: 'bodyweight' },
    { name: 'Mountain climbers', equipment: 'bodyweight' },
    { name: 'Hollow body hold', equipment: 'bodyweight' },
    { name: 'Sit-up', equipment: 'bodyweight' },
    { name: 'V-ups', equipment: 'bodyweight' },
    { name: 'Bicycle crunch', equipment: 'bodyweight' },
    { name: 'Toes to bar', equipment: 'bodyweight' },
  ],
  hombro: [
    { name: 'Barbell overhead press', equipment: 'barbell' },
    { name: 'Dumbbell shoulder press', equipment: 'dumbbell' },
    { name: 'Arnold press', equipment: 'dumbbell' },
    { name: 'Behind-the-neck press', equipment: 'barbell' },
    { name: 'Lateral raise', equipment: 'dumbbell' },
    { name: 'Cable lateral raise', equipment: 'cable' },
    { name: 'Front raise', equipment: 'dumbbell' },
    { name: 'Plate front raise', equipment: 'dumbbell' },
    { name: 'Reverse flyes', equipment: 'dumbbell' },
    { name: 'Cable reverse flyes', equipment: 'cable' },
    { name: 'Face pull', equipment: 'cable' },
    { name: 'Upright row', equipment: 'barbell' },
    { name: 'Y-raise', equipment: 'dumbbell' },
    { name: 'Cuban press', equipment: 'dumbbell' },
  ],
  biceps: [
    { name: 'Barbell curl', equipment: 'barbell' },
    { name: 'Dumbbell curl', equipment: 'dumbbell' },
    { name: 'Hammer curl', equipment: 'dumbbell' },
    { name: 'Cable curl', equipment: 'cable' },
    { name: 'Concentration curl', equipment: 'dumbbell' },
    { name: 'Preacher curl', equipment: 'barbell' },
    { name: 'Cable Bayesian curl', equipment: 'cable' },
    { name: '21s curl', equipment: 'barbell' },
    { name: 'Incline curl', equipment: 'dumbbell' },
    { name: 'EZ-bar curl', equipment: 'barbell' },
    { name: 'Spider curl', equipment: 'barbell' },
    { name: 'Reverse curl', equipment: 'barbell' },
    { name: 'Drag curl', equipment: 'barbell' },
  ],
  triceps: [
    { name: 'Rope pushdown', equipment: 'cable' },
    { name: 'Straight-bar pushdown', equipment: 'cable' },
    { name: 'Skull crushers', equipment: 'barbell' },
    { name: 'Overhead dumbbell extension', equipment: 'dumbbell' },
    { name: 'Overhead cable extension', equipment: 'cable' },
    { name: 'Bench dips', equipment: 'bodyweight' },
    { name: 'Dips', equipment: 'bodyweight' },
    { name: 'Close-grip bench press', equipment: 'barbell' },
    { name: 'Tricep kickback', equipment: 'dumbbell' },
    { name: 'Single-arm cable extension', equipment: 'cable' },
    { name: 'JM press', equipment: 'barbell' },
    { name: 'Diamond push-up', equipment: 'bodyweight' },
  ],
  cuadriceps: [
    { name: 'Back squat', equipment: 'barbell' },
    { name: 'Front squat', equipment: 'barbell' },
    { name: 'Hack squat', equipment: 'machine' },
    { name: 'Bulgarian split squat', equipment: 'dumbbell' },
    { name: 'Goblet squat', equipment: 'dumbbell' },
    { name: 'Sumo squat', equipment: 'dumbbell' },
    { name: 'Leg press', equipment: 'machine' },
    { name: 'Single-leg press', equipment: 'machine' },
    { name: 'Lunges', equipment: 'bodyweight' },
    { name: 'Walking lunges', equipment: 'bodyweight' },
    { name: 'Reverse lunges', equipment: 'bodyweight' },
    { name: 'Leg extension', equipment: 'machine' },
    { name: 'Step-up', equipment: 'dumbbell' },
    { name: 'Sissy squat', equipment: 'bodyweight' },
    { name: 'Zercher squat', equipment: 'barbell' },
    { name: 'Pause squat', equipment: 'barbell' },
    { name: 'Wall sit', equipment: 'bodyweight' },
  ],
  isquios: [
    { name: 'Lying leg curl', equipment: 'machine' },
    { name: 'Seated leg curl', equipment: 'machine' },
    { name: 'Standing leg curl', equipment: 'machine' },
    { name: 'Romanian deadlift', equipment: 'barbell' },
    { name: 'Stiff-leg deadlift', equipment: 'barbell' },
    { name: 'Nordic curl', equipment: 'bodyweight' },
    { name: 'Good morning', equipment: 'barbell' },
    { name: 'Glute-ham raise', equipment: 'machine' },
    { name: 'Single-leg Romanian deadlift', equipment: 'dumbbell' },
  ],
  gluteo: [
    { name: 'Hip thrust', equipment: 'barbell' },
    { name: 'Barbell hip thrust', equipment: 'barbell' },
    { name: 'Glute bridge', equipment: 'bodyweight' },
    { name: 'Single-leg glute bridge', equipment: 'bodyweight' },
    { name: 'Cable glute kickback', equipment: 'cable' },
    { name: 'Bulgarian split squat', equipment: 'dumbbell' },
    { name: 'Hip abduction', equipment: 'machine' },
    { name: 'Sumo deadlift', equipment: 'barbell' },
    { name: 'Weighted step-up', equipment: 'dumbbell' },
    { name: 'Frog pump', equipment: 'bodyweight' },
    { name: 'Cable pull-through', equipment: 'cable' },
  ],
  aductores: [
    { name: 'Adductor machine', equipment: 'machine' },
    { name: 'Sumo squat', equipment: 'dumbbell' },
    { name: 'Copenhagen plank', equipment: 'bodyweight' },
    { name: 'Cable adduction', equipment: 'cable' },
    { name: 'Side lunge', equipment: 'bodyweight' },
    { name: 'Cossack squat', equipment: 'bodyweight' },
  ],
  abductores: [
    { name: 'Abductor machine', equipment: 'machine' },
    { name: 'Standing leg raise', equipment: 'bodyweight' },
    { name: 'Monster walk (band)', equipment: 'bodyweight' },
    { name: 'Cable hip abduction', equipment: 'cable' },
    { name: 'Clamshell with band', equipment: 'bodyweight' },
    { name: 'Fire hydrant', equipment: 'bodyweight' },
  ],
  gemelos: [
    { name: 'Standing calf raise', equipment: 'machine' },
    { name: 'Seated calf raise', equipment: 'machine' },
    { name: 'Leg press calf raise', equipment: 'machine' },
    { name: 'Single-leg calf raise', equipment: 'bodyweight' },
    { name: 'Smith machine calf raise', equipment: 'machine' },
  ],
};
